name: Pytest

on:
  push:
    branches:
      - main  # Modify this to match the branch you want to trigger the workflow on
  pull_request:
    branches:
      - main  # Modify this to match the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Modify this to match the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Modify this if you have a specific requirements file
          pip install -r requirements-dev.txt
          pip install -e .

      - name: Run pytest
        run: pytest




